### ISSUE TITLE
"privacy restrictions" hyperlink in cmdrs-guide.html doesn't work

### ISSUE THREAD

**Issue by norohind** [EDCD/EDCD.github.io#7]
Steps to reproduce:

1. Go to https://edcd.github.io/cmdrs-guide.html
2. Go to end of the page
3. Find there `privacy restrictions` hyperlink 
4. Press it
5. See how nothing happens, it's broken

**Comment by Tkael** [comment]
The link may have been broken by https://github.com/EDCD/EDCD.github.io/commit/48dbe42b3e98b8b9fb172c13b45fcf09dd3167bf?

**Comment by norohind** [comment]
Seems like you're right.

**Comment by SayakMukhopadhyay** [comment]
Sorry for the super delayed response. Its not really broken. Because of how id links are handled, if the target is already visible, then the page is not scrolled anymore. You can test that the hyperlink is not broken by opening the page on a mobile or making the browser window smaller.

I have tested this and it is working as expected hence it would be great if a member can close this issue. @Tkael

**Comment by norohind** [comment]
Indeed, thank you, closing issue!
